<a href="https://colab.research.google.com/github/nighteye2/machine-learning-notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

numpy is the scientific computing library in python. it provides support for arrays and matrices along with a collection of mathematical function to operate on this data structures.

In [5]:
import numpy as np
#create arrays using numpy
arr1 = np.array([1,2,3])#this is 1d array
print(type(arr1))
print(arr1)
print(arr1.shape)#gives the shape of array

<class 'numpy.ndarray'>
[1 2 3]
(3,)


In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])#it is 2d array
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
arr3 = np.array([1,2,3])
arr3.reshape(1,3)#this means 1 row and 3 columns

array([[1, 2, 3]])

In [16]:
np.arange(0,10,1).reshape(2,5)#first number is rows and second number is column no

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
#predefined functions
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
arr4=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr4.size) # gives total number of elements present in the array
print(arr4.ndim) #gives the number of dimensions of the array

10
2


In [30]:
#numpy vectorised operations
array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('element wise operations \n')
print('addition =\n',array2+array1)
print('substraction =\n',array2-array1)
print('multiplication =\n',array2*array1)
print('division =\n',array2/array1)

element wise operations 

addition =
 [[ 11  22  33  44  55]
 [ 66  77  88  99 110]]
substraction =
 [[ 9 18 27 36 45]
 [54 63 72 81 90]]
multiplication =
 [[  10   40   90  160  250]
 [ 360  490  640  810 1000]]
division =
 [[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]


In [31]:
#universal functions
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
# sqaure root
print(np.sqrt(array1))
# exponential
print(np.exp(array1))
# sine
print(np.sin(array1))
# natural log
print(np.log(array1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [40]:
# array slicing and indexing
array1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print('array =\n',array1)
print(array1[0,0])
print(array1[0,1])
print(array1[0,2])
print(array1[0,3])
print(array1[0,4])

print(array1[1:,0:])
print('\n')
print(array1[0:2,0:2])
print('\n')
print(array1[0:2,3:])

array =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1
2
3
4
5
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


[[1 2]
 [6 7]]


[[ 4  5]
 [ 9 10]
 [14 15]]


In [41]:
from os.path import normcase
#statistical concepts = normalization

array1 = np.array([1,2,3,4,5])

#mean
mean = np.mean(array1)
print('mean = ',mean)

#median
median = np.median(array1)
print('median = ',median)

#standard deviation
std = np.std(array1)
print('standard deviation = ',std)

#variance
var = np.var(array1)
print('variance = ',var)

#normalised data
normalised_data = (array1-mean)/std
print('normalised data = ',normalised_data)

mean =  3.0
median =  3.0
standard deviation =  1.4142135623730951
variance =  2.0
normalised data =  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
#logical operation
data = np.array([1,2,3,4,5])
print(data>2)
print(data[data>2])

[False False  True  True  True]
[3 4 5]


In [43]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data1 = data[(data>3) & (data<8)]
print(data1)

[4 5 6 7]


In [1]:
import numpy as np

def page_rank(adj_matrix: np.ndarray, num_iterations: int = 100, d: float = 0.85):
    n = adj_matrix.shape[0]  # Nodes
    pagerank = np.ones(n) / n  # Init
    row_sums = adj_matrix.sum(axis=1)  # Sums
    norm_adj_matrix = adj_matrix / row_sums[:, np.newaxis]  # Normalize

    for _ in range(num_iterations):  # Iterate
        pagerank = (1 - d) / n + d * norm_adj_matrix.T.dot(pagerank)  # Update

    return pagerank  # Return

if __name__ == "__main__":
    adj_matrix = np.array([  # Matrix
        [0, 1, 1],
        [0, 0, 1],
        [1, 0, 0]
    ])

    pagerank_values = page_rank(adj_matrix)  # Calculate
    print("PageRank values:", pagerank_values)  # Output


PageRank values: [0.38778971 0.21481063 0.39739966]
